# PDF Manager User Application
spring:
  application:
    name: pdf-manager-user
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true